// All UI strings in English and Chinese.
// Loaded before data.js and app.js.

const UI = {
  en: {
    brandSub:           'Interior & Exterior Price Calculator',
    reset:              'Reset',
    printEstimate:      'Print Estimate',
    interior:           'Interior',
    exterior:           'Exterior',
    comingSoon:         'Coming Soon',
    selectComponents:   'Select Components',
    configureItems:     'Configure Selected Items',
    estimateSummary:    'Estimate Summary',
    emptyPrompt:        'Select components on the left to begin your estimate.',
    componentEstimate:  'Component estimate:',
    estimatedTotal:     'Estimated Total',
    disclaimer:         'Prices are estimates only. Actual costs vary by site conditions, local labour rates, and material availability. Consult a contractor for a firm quote.',
    // Bathroom UI
    bathrooms:          'Bathrooms',
    addBathroom:        '+ Add Bathroom',
    labour:             'Labour',
    materialsFixtures:  'Materials & Fixtures',
    numWorkers:         '# of Workers',
    ratePerDay:         'Rate per Day ($)',
    numDays:            '# of Days',
    labourTotal:        'Labour total:',
    noItemsYet:         'No items added yet. Use the menu below to add.',
    addItemPrompt:      '+ Add item…',
    allItemsAdded:      'All items added',
    bathroomTotal:      'Bathroom Total',
    colItem:            'Item',
    colQty:             'Qty',
    colUnitPrice:       'Unit $',
    colTotal:           'Total',
    removeBtn:          '✕ Remove',
    bathroomCount:      (n) => `Bathrooms (${n})`,
    bathroomSummary:    (n, items) => `${n} bathroom${n !== 1 ? 's' : ''} · ${items} line item${items !== 1 ? 's' : ''}`,
  },
  zh: {
    brandSub:           '室内外装修报价计算器',
    reset:              '重置',
    printEstimate:      '打印报价',
    interior:           '室内',
    exterior:           '室外',
    comingSoon:         '即将推出',
    selectComponents:   '选择项目',
    configureItems:     '配置已选项目',
    estimateSummary:    '报价摘要',
    emptyPrompt:        '请在左侧选择项目以开始估价。',
    componentEstimate:  '项目估算：',
    estimatedTotal:     '预估总价',
    disclaimer:         '以上价格仅供参考，实际费用因现场条件、当地人工费率及材料供应情况而异。如需准确报价，请咨询承包商。',
    // Bathroom UI
    bathrooms:          '浴室',
    addBathroom:        '+ 添加浴室',
    labour:             '人工',
    materialsFixtures:  '材料与设备',
    numWorkers:         '工人数量',
    ratePerDay:         '日薪 ($)',
    numDays:            '天数',
    labourTotal:        '人工小计：',
    noItemsYet:         '暂无项目，请使用下方菜单添加。',
    addItemPrompt:      '+ 添加项目…',
    allItemsAdded:      '所有项目已添加',
    bathroomTotal:      '浴室小计',
    colItem:            '项目',
    colQty:             '数量',
    colUnitPrice:       '单价',
    colTotal:           '合计',
    removeBtn:          '✕ 移除',
    bathroomCount:      (n) => `浴室 (${n})`,
    bathroomSummary:    (n, items) => `${n} 间浴室 · ${items} 个项目`,
  }
};
